# file: postgresql/tasks/extensions/contrib.yml

- name: PostgreSQL | Extensions | Make sure the postgres contrib extensions are installed | RedHat
  yum:
    name: "postgresql{{postgresql_version_terse}}-contrib"
    state: present
  when: ansible_os_family == "RedHat"
  notify:
    - restart postgresql
