# file: postgresql/tasks/main.yml

- import_tasks: install_yum.yml
  when: ansible_pkg_mgr == "yum"
  tags: [postgresql, postgresql-install]

- import_tasks: extensions.yml
  tags: [postgresql, postgresql-extensions]

- import_tasks: configure.yml
  tags: [postgresql, postgresql-configure]

- import_tasks: users.yml
  tags: [postgresql, postgresql-users]

- import_tasks: databases.yml
  tags: [postgresql, postgresql-databases]

- import_tasks: users_privileges.yml
  tags: [postgresql, postgresql-users]

- import_tasks: cleanup_archive.yml
  tags: [postgresql, postgresql-cleanup]

- import_tasks: dependency.yml
  when: ansible_os_family == "RedHat"
  tags: [postgresql, postgresql-deps]