# file: postgresql/tasks/main.yml

- include: install_yum.yml
  when: ansible_pkg_mgr == "yum"
  tags: [postgresql, postgresql-install]

- include: extensions.yml
  tags: [postgresql, postgresql-extensions]

- include: configure.yml
  tags: [postgresql, postgresql-configure]

- include: users.yml
  tags: [postgresql, postgresql-users]

- include: databases.yml
  tags: [postgresql, postgresql-databases]

- include: users_privileges.yml
  tags: [postgresql, postgresql-users]