# file: postgresql/handlers/main.yml

- name: restart postgresql
  service:
    name: "{{ postgresql_service_name }}"
    state: restarted
  listen: "restart postgresql"

- name: daemon reload
  systemd: daemon_reload=yes